name: Availability cron

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping cron-availability
        run: |
          curl -sf -X POST https://tere.co.nz/api/cron-availability
